version: '3.7'

services:
  record:
    build: .
    env_file: 
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${ARCHIVE}:/download
    command: ${TWITCASTING_ID}
    # logging:
    #   driver: "gelf"
    #   options:
    #     gelf-address: "udp://127.0.0.1:12201"
