version: '3.7'

services:
  twitcasting-recorder:
    image: ghcr.io/jim60105/twitcasting-recorder
    # build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ${ARCHIVE}:/download
    command: ${TWITCASTING_ID}
