services:
  twitcasting-recorder:
    container_name: twitcasting-recorder
    image: ghcr.io/jim60105/twitcasting-recorder
    user: "1001:0"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=1001
      cache_from:
        - ghcr.io/jim60105/twitcasting-recorder:cache
      cache_to:
        - type=inline
    restart: always
    env_file:
      - .env
    volumes:
      - ${ARCHIVE}:/download
    command: ${TWITCASTING_ID}
